name: dev-ci
on:
    push:
        paths-ignore:
            - '**/*.md'
        branches-ignore:
            - main
    pull_request:
        branches-ignore:
            - main

jobs:
    dev-build:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            # env
            - name: checkout code
              uses: actions/checkout@v6
            - name: setup pnpm
              uses: pnpm/action-setup@v5
            - name: setup node
              uses: actions/setup-node@v6
              with:
                  node-version: 24
                  cache: pnpm
                  cache-dependency-path: pnpm-lock.yaml
            - name: install dependencies
              run: pnpm install --frozen-lockfile

            # build
            - name: build
              run: pnpm run build
            - name: add doc
              run: cp LICENSE README.md CHANGELOG.md dist/
            - name: list files
              run: ls -lah dist/

            # 上传产物
            - name: upload-artifact
              uses: actions/upload-artifact@v6
              with:
                  name: bilibili-cleaner
                  path: dist/*
